#!/bin/bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"
./venv/bin/python3 -m piper.http_server -m ./models/en_US-libritts_r-medium.onnx --port 5111
