# The Docker image that will be used to build your app
image: node:lts
build:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  before_script: []
  script:
    - mkdir public
    - cp -r ocr_web public/ocr_web
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - apt install -y clang
    - . $HOME/.cargo/env; ./build_scripts/wasm-once.sh os3bevy rireki
    - mkdir public/rireki_web
    - cp ./os3bevy/wasm/rireki/rireki_bg.wasm public/rireki_web
    - cp ./os3bevy/wasm/rireki/index.html public/rireki_web
    - cp ./os3bevy/wasm/rireki/rireki.js public/rireki_web
    - cp -r ./os3bevy/assets public/rireki_web
  artifacts:
    expire_in: 1 hour
