[package]
name = "bevy_mod_audio"
version = "0.1.0"
edition = "2024"
description = "streaming spatial audio and microphone support for bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MalekiRe/bevy_mod_audio"

[dependencies]
bevy = "0.19.1"
cpal = "0.17.3"
flume = "0.12.0"
rodio = "0.22.2"

[target.'cfg(target_arch="wasm32")'.dependencies]
cpal = { version = "0.17.3", features = ["wasm-bindgen"] }
wasm-bindgen = "=0.2.129"
web-sys = { version = "=0.3.106", features = ["MediaStream","MediaStreamAudioSourceNode","MediaStreamConstraints","AudioProcessingEvent","Navigator", "Window", "ScriptProcessorNode", "MediaDevices"] }
